"""OPT: Make id to be uuid(4)

Revision ID: 04bf4aa1dba4
Revises: 0ac6b251dcdd
Create Date: 2024-09-25 10:26:11.502085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bf4aa1dba4'
down_revision = '0ac6b251dcdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('featured_projects', schema=None) as batch_op:
        batch_op.alter_column('featured_project_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('featured_projects', schema=None) as batch_op:
        batch_op.alter_column('featured_project_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
