"""improve resume table

Revision ID: 0ac6b251dcdd
Revises: 58491bccf4a3
Create Date: 2024-08-31 20:06:39.867973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac6b251dcdd'
down_revision = '58491bccf4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_image1_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('resume_image2_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('resume_image3_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('resume_image4_link', sa.String(length=255), nullable=True))
        batch_op.drop_column('resume_page1_link')
        batch_op.drop_column('resume_page2_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_page2_link', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('resume_page1_link', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('resume_image4_link')
        batch_op.drop_column('resume_image3_link')
        batch_op.drop_column('resume_image2_link')
        batch_op.drop_column('resume_image1_link')

    # ### end Alembic commands ###
