"""added video_url to featured projects

Revision ID: 128c950aad0b
Revises: ff31d1ffed10
Create Date: 2024-08-30 11:11:39.622706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128c950aad0b'
down_revision = 'ff31d1ffed10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('featured_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_link', sa.String(length=2083), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('featured_projects', schema=None) as batch_op:
        batch_op.drop_column('video_link')

    # ### end Alembic commands ###
