"""added video demo to projects done

Revision ID: 58491bccf4a3
Revises: 128c950aad0b
Create Date: 2024-08-30 12:29:58.801571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58491bccf4a3'
down_revision = '128c950aad0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_done', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_link', sa.String(length=2083), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects_done', schema=None) as batch_op:
        batch_op.drop_column('video_link')

    # ### end Alembic commands ###
