"""OPT: Change id to uud4

Revision ID: 6802f97bb580
Revises: 04bf4aa1dba4
Create Date: 2024-09-25 11:20:30.397583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6802f97bb580'
down_revision = '04bf4aa1dba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactMessage', schema=None) as batch_op:
        batch_op.alter_column('message_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('projects_done', schema=None) as batch_op:
        batch_op.alter_column('project_done_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('reference', schema=None) as batch_op:
        batch_op.alter_column('reference_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.alter_column('resume_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('writings', schema=None) as batch_op:
        batch_op.alter_column('writing_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writings', schema=None) as batch_op:
        batch_op.alter_column('writing_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.alter_column('resume_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('reference', schema=None) as batch_op:
        batch_op.alter_column('reference_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('projects_done', schema=None) as batch_op:
        batch_op.alter_column('project_done_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('contactMessage', schema=None) as batch_op:
        batch_op.alter_column('message_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
