"""OPT: uuid4 as id for admin

Revision ID: 706820ee9548
Revises: 6802f97bb580
Create Date: 2024-09-25 11:35:22.272989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706820ee9548'
down_revision = '6802f97bb580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
