"""FEAT: modified writing table

Revision ID: 70f3a00042da
Revises: a825f62883fe
Create Date: 2024-08-18 10:18:47.164091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f3a00042da'
down_revision = 'a825f62883fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=2083),
               existing_nullable=True)
        batch_op.alter_column('domain_link',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=2083),
               existing_nullable=True)
        batch_op.alter_column('github_link',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=2083),
               existing_nullable=True)

    with op.batch_alter_table('writings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_link', sa.String(length=2083), nullable=True))
        batch_op.alter_column('published_link',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=2083),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writings', schema=None) as batch_op:
        batch_op.alter_column('published_link',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
        batch_op.drop_column('image_link')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('github_link',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
        batch_op.alter_column('domain_link',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
        batch_op.alter_column('image_link',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###
