"""OPT: make image_link Optional

Revision ID: a825f62883fe
Revises: 677dd48a7ee7
Create Date: 2024-08-16 20:12:18.991546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a825f62883fe'
down_revision = '677dd48a7ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('image_link',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)

    # ### end Alembic commands ###
