"""Feat: alot of changes

Revision ID: ff31d1ffed10
Revises: 70f3a00042da
Create Date: 2024-08-20 13:28:03.552982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff31d1ffed10'
down_revision = '70f3a00042da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('date_updated', sa.DATETIME(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('image_link', sa.VARCHAR(length=2083), nullable=True),
    sa.Column('stacks', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('domain_link', sa.VARCHAR(length=2083), nullable=True),
    sa.Column('github_link', sa.VARCHAR(length=2083), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###
